import RootLayout from "@/app/rootLayout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  //const selectedProjectId = cookies().get("selected_project")?.value;

  return (
    <html lang="en">
      <head></head>
      <body>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
